#Data sourced from https://www.semrush.com and https://tools.wordstream.com/
data = [
    {
        'name': 'Disney',
        'search_count': 2745000,
        'description': 'media entertainment company',
        'country': 'the United States',
    },
    {
        'name': 'Instagram',
        'search_count': 30400000,
        'description': 'social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Cristiano Ronaldo',
        'search_count': 1220000,
        'description': 'footballer',
        'country': 'Portugal',
    },
    {
        'name': 'Elizabeth Olsen',
        'search_count': 2600000,
        'description': 'actress',
        'country': 'the United States',
    },
    {
        'name': 'Chris Brown',
        'search_count': 895000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Wikipedia',
        'search_count': 2748000,
        'description': 'online encyclopedia',
        'country': 'around the world',
    },
    {
        'name': 'LeBron James',
        'search_count': 2740000,
        'description': 'basketball player',
        'country': 'the United States',
    },
    {
        'name': 'Sony',
        'search_count': 574000,
        'description': 'multinational conglomerate company',
        'country': 'Japan',
    },
    {
        'name': 'Vin Diesel',
        'search_count': 673000,
        'description': 'actor',
        'country': 'the United States',
    },
    {
        'name': 'Ariana Grande',
        'search_count': 4090000,
        'description': 'musician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Reddit',
        'search_count': 9140000,
        'description': 'social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Dwayne Johnson',
        'search_count': 1000000,
        'description': 'actor and professional wrestler',
        'country': 'the United States',
    },
    {
        'name': 'Google',
        'search_count': 68000000,
        'description': 'technology company',
        'country': 'the United States',
    },
    {
        'name': 'Robert Downey Jr',
        'search_count': 685000,
        'description': 'actor',
        'country': 'the United States',
    },
    {
        'name': 'TikTok',
        'search_count': 11100000,
        'description': 'social media platform',
        'country': 'the United States and China',
    },
    {
        'name': 'Selena Gomez',
        'search_count': 2240000,
        'description': 'ausician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Apple',
        'search_count': 6120000,
        'description': 'technology company',
        'country': 'the United States',
    },
    {
        'name': 'Chris Evans',
        'search_count': 1320000,
        'description': 'actor',
        'country': 'the United States',
    },
    {
        'name': 'Kim Kardashian',
        'search_count': 3350000,
        'description': 'reality TV personality and businesswoman',
        'country': 'the United States',
    },
    {
        'name': 'Scarlett Johansson',
        'search_count': 2550000,
        'description': 'actress',
        'country': 'the United States',
    },
    {
        'name': 'Lionel Messi',
        'search_count': 1250000,
        'description': 'footballer',
        'country': 'Argentina',
    },
    {
        'name': 'Marvel',
        'search_count': 1005000,
        'description': 'large publisher in the comics industry',
        'country': 'the United States',
    },
    {
        'name': 'DC',
        'search_count': 305000,
        'description': 'large publisher in the comics industry',
        'country': 'the United States',
    },
    {
        'name': 'Leonardo DiCaprio',
        'search_count': 1200000,
        'description': 'actor',
        'country': 'the United States',
    },
    {
        'name': 'Beyoncé',
        'search_count': 2250000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Discord',
        'search_count': 7485000,
        'description': 'social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Mark Rober',
        'search_count': 674000,
        'description': 'youtuber',
        'country': 'the United States',
    },
    {
        'name': 'Neymar',
        'search_count': 381000,
        'description': 'footballer',
        'country': 'Brazil',
    },
    {
        'name': 'National Geographic',
        'search_count': 246000,
        'description': 'magazine',
        'country': 'the United States',
    },
    {
        'name': 'Playstation',
        'search_count': 6040000,
        'description': 'video game console',
        'country': 'Japan',
    },
    {
        'name': 'Justin Bieber',
        'search_count': 3350000,
        'description': 'musician',
        'country': 'Canada',
    },
    {
        'name': 'Samsung',
        'search_count': 1930000,
        'description': 'technology company',
        'country': 'South Korea',
    },
    {
        'name': 'Taylor Swift',
        'search_count': 3400000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Olivia Rodrigo',
        'search_count': 4009000,
        'description': 'musician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Kendall Jenner',
        'search_count': 1220000,
        'description': 'reality TV personality and Model',
        'country': 'the United States',
    },
    {
        'name': 'Jennifer Lopez',
        'search_count': 1500000,
        'description': 'musician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Nicki Minaj',
        'search_count': 3450000,
        'description': 'musician',
        'country': 'Trinidad and Tobago',
    },
    {
        'name': 'Nike',
        'search_count': 7480000,
        'description': 'sportswear multinational',
        'country': 'the United States',
    },
    {
        'name': 'PewDiePie',
        'search_count': 1830000,
        'description': 'youtuber',
        'country': 'Sweden',
    },
    {
        'name': 'Spotify',
        'search_count': 6130000,
        'description': 'audio streaming service',
        'country': 'Sweden',
    },
    {
        'name': 'Khloé Kardashian',
        'search_count': 1210000,
        'description': 'reality TV personality and businesswoman',
        'country': 'the United States',
    },
    {
        'name': 'XBox',
        'search_count': 3354000,
        'description': 'video game console',
        'country': 'the United States',
    },
    {
        'name': 'Miley Cyrus',
        'search_count': 1450000,
        'description': 'musician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Katy Perry',
        'search_count': 1250000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Andrew Garfield',
        'search_count': 1830000,
        'description': 'actor and singer',
        'country': 'the United Kingdom',
    },
    {
        'name': 'Kourtney Kardashian',
        'search_count': 1550000,
        'description': 'reality TV personality',
        'country': 'the United States',
    },
    {
        'name': 'Microsoft',
        'search_count': 1835000,
        'description': 'technology company',
        'country': 'the United States',
    },
    {
        'name': 'Twitter',
        'search_count': 16550000,
        'description': 'social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Kevin Hart',
        'search_count': 1050000,
        'description': 'comedian and actor',
        'country': 'the United States',
    },
    {
        'name': 'Ellen DeGeneres',
        'search_count': 455000,
        'description': 'comedian',
        'country': 'the United States',
    },
    {
        'name': 'Real Madrid CF',
        'search_count': 115000,
        'description': 'football club',
        'country': 'Spain',
    },
    {
        'name': 'Twitch',
        'search_count': 6120000,
        'description': 'live streaming service',
        'country': 'the United States',
    },
    {
        'name': 'FC Barcelona',
        'search_count': 1150000,
        'description': 'football club',
        'country': 'Spain',
    },
    {
        'name': 'Minecraft',
        'search_count': 7480000,
        'description': 'sandbox video game',
        'country': 'Sweden',
    },
    {
        'name': 'Rihanna',
        'search_count': 2740000,
        'description': 'musician and businesswoman',
        'country': 'Barbados',
    },
    {
        'name': 'Chris Hemsworth',
        'search_count': 855000,
        'description': 'actor',
        'country': 'Australia',
    },
    {
        'name': 'Kylie Jenner',
        'search_count': 2230000,
        'description': 'reality TV personality and businesswoman and Self-Made Billionaire',
        'country': 'the United States',
    },
    {
        'name': 'Demi Lovato',
        'search_count': 1005000,
        'description': 'musician and actress',
        'country': 'the United States',
    },
    {
        'name': 'Ed Sheeran',
        'search_count': 1820000,
        'description': 'singer and songwriter',
        'country': 'the United Kingdom',
    },
    {
        'name': 'Jackie Chan',
        'search_count': 450000,
        'description': 'actor and martial artist',
        'country': 'China',
    },
    {
        'name': "Victoria's Secret",
        'search_count': 6120000,
        'description': 'lingerie brand',
        'country': 'the United States',
    },
    {
        'name': 'Snapchat',
        'search_count': 1834000,
        'description': 'social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Zendaya',
        'search_count': 3450000,
        'description': 'actress and musician',
        'country': 'the United States',
    },
    {
        'name': 'YouTube',
        'search_count': 185000000,
        'description': 'video sharing and social media platform',
        'country': 'the United States',
    },
    {
        'name': 'Tom Holland',
        'search_count': 2350000,
        'description': 'actor',
        'country': 'the United Kingdom',
    },
    {
        'name': 'Shakira',
        'search_count': 1000000,
        'description': 'musician',
        'country': 'Colombia',
    },
    {
        'name': 'Wii',
        'search_count': 301000,
        'description': 'video game console',
        'country': 'Japan',
    },
    {
        'name': 'Drake',
        'search_count': 4009000,
        'description': 'musician',
        'country': 'Canada',
    },
    {
        'name': 'The Weekend',
        'search_count': 2750000,
        'description': 'singer and producer',
        'country': 'Canada',
    },
    {
        'name': 'Cardi B',
        'search_count': 2730000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Roblox',
        'search_count': 13600000,
        'description': 'online game platform',
        'country': 'the United States',
    },
    {
        'name': 'David Beckham',
        'search_count': 256000,
        'description': 'footballer',
        'country': 'the United Kingdom',
    },
    {
        'name': 'Nintendo',
        'search_count': 4935000,
        'description': 'video game company',
        'country': 'Japan',
    },
    {
        'name': 'Billie Eilish',
        'search_count': 4080000,
        'description': 'musician',
        'country': 'the United States',
    },
    {
        'name': 'Justin Timberlake',
        'search_count': 675000,
        'description': 'musician and actor',
        'country': 'the United States',
    },
    {
        'name': 'UEFA Champions League',
        'search_count': 823000,
        'description': 'club football competition',
        'country': 'Europe',
    },
    {
        'name': 'Tesla',
        'search_count': 5000000,
        'description': 'automotive company',
        'country': 'the United States',
    },
    {
        'name': 'NASA',
        'search_count': 556000,
        'description': 'space agency',
        'country': 'the United States',
    },
    {
        'name': 'Emma Watson',
        'search_count': 1260000,
        'description': 'actress',
        'country': 'the United Kingdom',
    },
    {
        'name': 'Eminem',
        'search_count': 4001000,
        'description': 'rapper, songwriter and producer',
        'country': 'the United States',
    },
    {
        'name': 'Shawn Mendes',
        'search_count': 1045000,
        'description': 'musician',
        'country': 'Canada',
    },
    {
        'name': 'Virat Kohli',
        'search_count': 90500,
        'description': 'cricketer',
        'country': 'India',
    },
    {
        'name': 'Netflix',
        'search_count': 16600000,
        'description': 'streaming service and production company',
        'country': 'the United States',
    },
    {
        'name': 'Gigi Hadid',
        'search_count': 557000,
        'description': 'model',
        'country': 'the United States',
    },
    {
        'name': 'Grant Gustin',
        'search_count': 201000,
        'description': 'actor and singer',
        'country': 'the United States',
    },
    {
        'name': 'Ronaldinho',
        'search_count': 135000,
        'description': 'footballer',
        'country': 'Brazil',
    },
    {
        'name': 'Maluma',
        'search_count': 1010000,
        'description': 'musician',
        'country': 'Colombia',
    },
    {
        'name': 'Camila Cabello',
        'search_count': 1540000,
        'description': 'musician',
        'country': 'Cuba',
    },
    {
        'name': 'Pokemon',
        'search_count': 3365000,
        'description': 'media franchise',
        'country': 'Japan',
    },
    {
        'name': 'NBA',
        'search_count': 30400000,
        'description': 'club Basketball Competition',
        'country': 'the United States',
    },
]